<?php
// $Id$

/**
 * @file
 * Implements some keyword based rules for the SEO Checker.
 *
 */

/**
 * mplementation of hook_register_seo_rules()
 * @return (array) rules
 */
function keyword_rules_register_seo_rules() {
  $rules['keyword_density'] = array(
    'name' => 'Keyword density in the body',
    'description' => 'Checks the density of keywords over the the body of a page. Remark: too high density is not a good SEO.',
    'threshold type' => 'range',
    'default threshold' => array(5, 20),
    'callback' => 'keyword_rules_density',
    'passed feedback' => t('Test passed.'),
    'failed feedback' => t('Test failed, please make sure you use your keywords in the body but not too often.'),
  );
  return $rules;
}

/**
 * Dervies the densitiy of keywords within the body of the node.
 * @param object $form_values
 */
function keyword_rules_density($form_values) {
  $keyword_rules_field = variable_get('keyword_rules_field_'. $form_values['type'], 0);
  if ($keyword_rules_field === 'disabled') {
    return FALSE;
  }
  $keywords = $form_values[$keyword_rules_field][0]['value'];
  $tags = drupal_explode_tags($keywords);
  if (count($tags) == 0) {
    return 0;
  }
  $body = strip_tags($form_values['body']);
  $words = preg_split('/\W+/', $body);
  $total = count($words);
  $nr_of_tags = 0;
  foreach ($tags as $tag) {
    $pos=-1;
    while (($pos = seo_checker_wordipos($body, $tag, $pos+1)) !== FALSE) {
      $nr_of_tags++;
    }
  }
  return 100*$nr_of_tags/$total;
}

/**
 * The SEO Checker has to be enabled per content type
 */
function keyword_rules_form_node_type_form_alter(&$form, $form_status) {
  $fieldarr = field_info_instances($form['#node_type']->type);
  $fields['disabled'] = t('Disable Keyword Check');

  foreach ($fieldarr as $label => $field) {
    $fields[$label] = $field['field_name'];
  }

  $form['seo_checker']['keyword_rules_field'] = array(
    '#type' => 'select',
    '#title' => t('Field defining the keywords'),
    '#default_value' => variable_get('keyword_rules_field_'. $form['#node_type']->type, 0),
    '#description' => t('Select the field that defines the keywords to be used for the checks.'),
    '#options' => $fields,
  );
}